export const shopUrl = "/?skipIntro=1";

export const promos = [
  {
    id: "coming-home",
    theme: "Everyday ritual",
    why: "Ananya wants a small, believable pause when she comes home. Amber incense is distinctive, low-commitment and easy to picture in her living room.",
    product: "Amber Incense Sticks",
    collection: "Encens d’Auroville",
    price: "₹260",
    url: "/product/2950",
    fact: "Phthalate, propylene glycol and charcoal free. Fair Trade. 10 sticks.",
    headline: "A little time that belongs to you.",
    body: "Light Amber when the day loosens. A warm, resinous home scent from Encens d’Auroville, handmade in Auroville.",
    platforms: [
      {
        name: "Instagram feed",
        format: "Portrait still, 1080 x 1350",
        note: "Show the orange Encens d’Auroville pack on a teak table at dusk. Lead with the moment, then the pack.",
      },
      {
        name: "Instagram Stories",
        format: "Vertical, 1080 x 1920",
        note: "Three frames: lighting the stick, the room filling, a close pack shot with the line.",
      },
      {
        name: "WhatsApp",
        format: "Square image plus 2-line caption",
        note: "Send to existing customers as a restock note, not a blast offer.",
      },
    ],
    productImage: "/marketing/products/amber-incense.jpg",
    formatImage: "/marketing/promos/format-feed-amber-incense.jpg",
    formatLabel: "Feed still · 3:4",
    formatRatio: "portrait",
  },
  {
    id: "pulse-point",
    theme: "Personal fragrance",
    why: "She wants a scent that feels like her and that she can use in an ordinary day. A pulse-point roll-on is private, portable and easy to explain.",
    product: "Bliss Aromatherapy Roll-On Perfume",
    collection: "Perfumes",
    price: "₹550",
    url: "/product/1004630",
    fact: "Orange, patchouli and Indian borage. 10 ml pulse-point roll-on. 100% natural botanicals.",
    headline: "Find a fragrance that feels like you.",
    body: "Orange, patchouli and Indian borage on the wrist. A cheerful, comforting oil she can roll on between meetings or before she leaves the house.",
    platforms: [
      {
        name: "Instagram Stories / Reels",
        format: "Vertical, 1080 x 1920",
        note: "Close wrist application, then a breath in, then the bottle. Keep the scent notes on screen.",
      },
      {
        name: "WhatsApp / carousel",
        format: "Square, 1080 x 1080",
        note: "Clean pack shot with the three notes. Use as the first frame of a fragrance guide.",
      },
      {
        name: "Site PDP and email",
        format: "Product photo plus 3 scent notes",
        note: "Answer 'what will this smell like?' before the add-to-basket button.",
      },
    ],
    productImage: "/marketing/products/bliss-rollon.jpg",
    formatImage: "/marketing/promos/format-story-bliss.jpg",
    formatLabel: "Stories / Reels · 9:16",
    formatRatio: "story",
  },
  {
    id: "champak-gift",
    theme: "Thoughtful gifting",
    why: "She gives gifts that feel personally considered. Champak is a distinctive Indian flower, the set is ready to wrap, and the contents are a complete home ritual.",
    product: "Champak Essential Gift Set",
    collection: "Gifting",
    price: "₹760",
    url: "/product/1001203",
    fact: "Champak Flower leaf incense, votive candle and incense holder in a ready gift box.",
    headline: "For someone whose tastes you know by heart.",
    body: "A small Champak ritual: leaf incense, a votive and a holder. Show the exact contents so she can give it with confidence.",
    platforms: [
      {
        name: "Instagram feed",
        format: "Portrait still, 1080 x 1350",
        note: "Open the yellow box. Show lid, votive, leaves and holder. Caption lists every item.",
      },
      {
        name: "Email",
        format: "Landscape header, 1200 x 675",
        note: "Gift landing for a friend, sister or host. Separate from self-purchase messages.",
      },
      {
        name: "WhatsApp and site /gifting",
        format: "Open-box photo plus contents list",
        note: "Include size of the box and that it arrives ready to give.",
      },
    ],
    productImage: "/marketing/products/champak-gift.jpg",
    formatImage: "/marketing/promos/format-feed-champak-gift.jpg",
    formatLabel: "Feed still · 3:4",
    formatRatio: "portrait",
  },
  {
    id: "amber-glow",
    theme: "Seasonal gift",
    why: "When she is buying for festivals or year-end, she wants a warmer, more complete ritual, not a generic hamper. Name every item in the box.",
    product: "Amber Glow Gift Set",
    collection: "Gifting",
    price: "₹1,565",
    url: "/product/1002319",
    fact: "Includes Sweet Amber Ambient Perfume, three leaf-shaped incense, ceramic incense holder and a scented vegetable wax votive.",
    headline: "A gift with a ritual inside.",
    body: "Sweet Amber perfume, leaf incense, a ceramic holder and a votive. Designed for gentle, everyday unwinding, ready to give.",
    platforms: [
      {
        name: "Email header",
        format: "Landscape, 1200 x 675",
        note: "Open the red box. Put the contents list in the email body, not only on the image.",
      },
      {
        name: "Instagram feed",
        format: "Portrait still of the open box",
        note: "Use for Diwali, Christmas and host gifts. Do not run it year-round as the lid says Season’s Greetings.",
      },
      {
        name: "Site /gifting",
        format: "PDP with contents listed above the fold",
        note: "Answer 'will this make a good gift?' with items, presentation and price.",
      },
    ],
    productImage: "/marketing/products/amber-glow-gift.jpg",
    formatImage: "/marketing/promos/format-email-amber-glow.jpg",
    formatLabel: "Email header · 16:9",
    formatRatio: "wide",
  },
] as const;
