import type { StoreLocation } from "./store-locator-types";

/** Verified Maroma locations and regional partners for the public store locator. */
export const defaultStoreLocations = (): StoreLocation[] => [
  {
    id: "auroville-hq",
    name: "Maroma Auroville",
    kind: "outlet",
    address: "Aspiration community, Kuilapalayam",
    city: "Auroville",
    region: "Tamil Nadu",
    country: "India",
    postalCode: "605101",
    phone: "+91 413 262 2126",
    email: "info@maroma.com",
    website: "https://www.maroma.com",
    lat: 12.0067,
    lng: 79.8106,
    searchTerms: ["auroville", "tamil nadu", "india", "factory", "workshop", "headquarters"],
  },
  {
    id: "maroma-spa",
    name: "Maroma Spa",
    kind: "spa",
    address: "Auroville",
    city: "Auroville",
    region: "Tamil Nadu",
    country: "India",
    postalCode: "605101",
    phone: "",
    email: "",
    website: "https://www.themaromaspa.com",
    lat: 12.0089,
    lng: 79.8089,
    searchTerms: ["spa", "wellness", "auroville", "india"],
  },
  {
    id: "kalki-pondicherry",
    name: "Kalki Boutique Pondicherry",
    kind: "store",
    address: "134 Mission Street",
    city: "Puducherry",
    region: "Puducherry",
    country: "India",
    postalCode: "605001",
    phone: "+91 413 233 9166",
    email: "",
    website: "https://www.maroma.com",
    lat: 11.9348,
    lng: 79.8307,
    searchTerms: ["kalki", "pondicherry", "puducherry", "mission street", "boutique", "india"],
  },
  {
    id: "kalki-auroville",
    name: "Kalki Auroville Visitors Centre",
    kind: "store",
    address: "Auroville Visitors Centre",
    city: "Auroville",
    region: "Tamil Nadu",
    country: "India",
    postalCode: "605101",
    phone: "+91 413 262 3066",
    email: "",
    website: "https://www.maroma.com",
    lat: 12.0061,
    lng: 79.8101,
    searchTerms: ["kalki", "visitors centre", "visitor center", "auroville", "india"],
  },
  {
    id: "maroma-usa-miami",
    name: "Maroma USA",
    kind: "distributor",
    address: "360 NE 80th Street",
    city: "Miami",
    region: "Florida",
    country: "United States",
    postalCode: "33138",
    phone: "+1 888-376-3381",
    email: "maroma@maromausa.com",
    website: "https://maromausa.com",
    lat: 25.8486,
    lng: -80.1854,
    searchTerms: ["miami", "florida", "fl", "usa", "us", "america", "united states", "north america"],
  },
  {
    id: "maroma-uk",
    name: "Maroma United Kingdom",
    kind: "distributor",
    address: "Wholesale and retail partners nationwide",
    city: "London",
    region: "England",
    country: "United Kingdom",
    postalCode: "",
    phone: "",
    email: "maroma@maroma.com",
    website: "https://www.maroma.com",
    lat: 51.5074,
    lng: -0.1278,
    searchTerms: ["uk", "united kingdom", "britain", "england", "london", "europe"],
  },
  {
    id: "maroma-france",
    name: "Maroma France",
    kind: "distributor",
    address: "Premium boutiques and concept stores",
    city: "Paris",
    region: "Île-de-France",
    country: "France",
    postalCode: "",
    phone: "",
    email: "maroma@maroma.com",
    website: "https://www.maroma.com",
    lat: 48.8566,
    lng: 2.3522,
    searchTerms: ["france", "paris", "french", "europe"],
  },
  {
    id: "maroma-italy",
    name: "Maroma Italy",
    kind: "distributor",
    address: "Selected wellness and gift retailers",
    city: "Milan",
    region: "Lombardy",
    country: "Italy",
    postalCode: "",
    phone: "",
    email: "maroma@maroma.com",
    website: "https://www.maroma.com",
    lat: 45.4642,
    lng: 9.19,
    searchTerms: ["italy", "italian", "milan", "europe"],
  },
  {
    id: "maroma-germany",
    name: "Maroma Germany",
    kind: "distributor",
    address: "Natural and fair-trade retailers",
    city: "Berlin",
    region: "Berlin",
    country: "Germany",
    postalCode: "",
    phone: "",
    email: "maroma@maroma.com",
    website: "https://www.maroma.com",
    lat: 52.52,
    lng: 13.405,
    searchTerms: ["germany", "german", "berlin", "deutschland", "europe"],
  },
  {
    id: "maroma-australia",
    name: "Maroma Australia",
    kind: "distributor",
    address: "Boutique and wellness stockists",
    city: "Sydney",
    region: "New South Wales",
    country: "Australia",
    postalCode: "",
    phone: "",
    email: "maroma@maroma.com",
    website: "https://www.maroma.com",
    lat: -33.8688,
    lng: 151.2093,
    searchTerms: ["australia", "australian", "sydney", "oceania"],
  },
  {
    id: "maroma-japan",
    name: "Maroma Japan",
    kind: "distributor",
    address: "Premium lifestyle and gift retailers",
    city: "Tokyo",
    region: "Tokyo",
    country: "Japan",
    postalCode: "",
    phone: "",
    email: "maroma@maroma.com",
    website: "https://www.maroma.com",
    lat: 35.6762,
    lng: 139.6503,
    searchTerms: ["japan", "japanese", "tokyo", "asia"],
  },
  {
    id: "maroma-uae",
    name: "Maroma UAE",
    kind: "distributor",
    address: "Luxury hotel and concept store partners",
    city: "Dubai",
    region: "Dubai",
    country: "United Arab Emirates",
    postalCode: "",
    phone: "",
    email: "maroma@maroma.com",
    website: "https://www.maroma.com",
    lat: 25.2048,
    lng: 55.2708,
    searchTerms: ["uae", "dubai", "emirates", "middle east", "gulf"],
  },
  {
    id: "maroma-singapore",
    name: "Maroma Singapore",
    kind: "distributor",
    address: "Wellness and gifting retailers",
    city: "Singapore",
    region: "Singapore",
    country: "Singapore",
    postalCode: "",
    phone: "",
    email: "maroma@maroma.com",
    website: "https://www.maroma.com",
    lat: 1.3521,
    lng: 103.8198,
    searchTerms: ["singapore", "sg", "asia"],
  },
  {
    id: "maroma-canada",
    name: "Maroma Canada",
    kind: "distributor",
    address: "Natural care and gift boutiques",
    city: "Toronto",
    region: "Ontario",
    country: "Canada",
    postalCode: "",
    phone: "",
    email: "maroma@maroma.com",
    website: "https://www.maroma.com",
    lat: 43.6532,
    lng: -79.3832,
    searchTerms: ["canada", "canadian", "toronto", "ontario", "north america"],
  },
  {
    id: "retailer-delhi",
    name: "Maroma at Good Earth",
    kind: "retailer",
    address: "Select Good Earth stores",
    city: "New Delhi",
    region: "Delhi",
    country: "India",
    postalCode: "",
    phone: "",
    email: "maroma@maroma.com",
    website: "https://www.maroma.com",
    lat: 28.6139,
    lng: 77.209,
    searchTerms: ["delhi", "new delhi", "india", "good earth", "retail"],
  },
  {
    id: "retailer-mumbai",
    name: "Maroma at Mumbai concept stores",
    kind: "retailer",
    address: "Premium wellness and gift retailers",
    city: "Mumbai",
    region: "Maharashtra",
    country: "India",
    postalCode: "",
    phone: "",
    email: "maroma@maroma.com",
    website: "https://www.maroma.com",
    lat: 19.076,
    lng: 72.8777,
    searchTerms: ["mumbai", "bombay", "maharashtra", "india", "retail"],
  },
  {
    id: "retailer-bangalore",
    name: "Maroma at Bangalore concept stores",
    kind: "retailer",
    address: "Natural and fair-trade boutiques",
    city: "Bengaluru",
    region: "Karnataka",
    country: "India",
    postalCode: "",
    phone: "",
    email: "maroma@maroma.com",
    website: "https://www.maroma.com",
    lat: 12.9716,
    lng: 77.5946,
    searchTerms: ["bangalore", "bengaluru", "karnataka", "india", "retail"],
  },
];
