import { NextResponse } from "next/server";
import { cookies } from "next/headers";
import { getSessionSecret, SESSION_COOKIE, verifySessionPayload } from "../../../../lib/auth-session";
import { readLiveStorefrontCatalog } from "../../../../lib/product-catalog-admin";
import { readShippingRestrictions, writeShippingRestrictions, type ShippingRestrictedRegion } from "../../../../lib/shipping-restrictions";
export const runtime = "nodejs";
async function admin() { const secret=getSessionSecret(); const token=cookies().get(SESSION_COOKIE)?.value; const session=secret&&token?await verifySessionPayload(token,secret):null; return session?.role === "admin"; }
export async function GET() { if (!(await admin())) return NextResponse.json({ error:"Admin sign-in required." },{status:401}); const [{products}, store] = await Promise.all([readLiveStorefrontCatalog(),readShippingRestrictions()]); return NextResponse.json({ regions:store.regions, products }); }
export async function POST(request:Request) { if (!(await admin())) return NextResponse.json({error:"Admin sign-in required."},{status:401}); try { const body=await request.json() as {action?:string; region?:Partial<ShippingRestrictedRegion>; id?:string}; const store=await readShippingRestrictions(); if(body.action==="delete") { store.regions=store.regions.filter((region)=>region.id!==body.id); await writeShippingRestrictions(store); return NextResponse.json({ok:true,regions:store.regions}); } const raw=body.region??{}; const id=raw.id && store.regions.some((region)=>region.id===raw.id)?raw.id:`region-${crypto.randomUUID()}`; const region:ShippingRestrictedRegion={id,name:String(raw.name??"").trim().slice(0,100),areas:Array.isArray(raw.areas)?raw.areas.map(String).map((item)=>item.trim()).filter(Boolean).slice(0,30):[],enabled:raw.enabled!==false,productIds:Array.isArray(raw.productIds)?raw.productIds.map(String).filter(Boolean).slice(0,800):[],includeLegacyTagged:raw.includeLegacyTagged===true}; if(!region.name||!region.areas.length) return NextResponse.json({error:"Add a region name and at least one matching location."},{status:400}); const index=store.regions.findIndex((item)=>item.id===id); if(index===-1) store.regions.push(region); else store.regions[index]=region; await writeShippingRestrictions(store); return NextResponse.json({ok:true,region,regions:store.regions}); } catch(error) { return NextResponse.json({error:error instanceof Error?error.message:"Unable to save restrictions."},{status:500}); } }
